CREATE TABLE IF NOT EXISTS western_blot_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id TEXT NOT NULL,
    candidate_key TEXT NOT NULL,
    source_pdf TEXT,
    candidate_path TEXT,
    page INTEGER NOT NULL CHECK (page > 0),
    figure_label TEXT,
    panel_label TEXT,
    row_index INTEGER,
    lane_index INTEGER,
    target TEXT NOT NULL,
    is_loading_control BOOLEAN NOT NULL DEFAULT FALSE,
    western_blot_type TEXT NOT NULL,
    sample TEXT,
    organism TEXT,
    treatment_context TEXT,
    condition TEXT,
    band_state TEXT NOT NULL CHECK (band_state IN ('present', 'absent', 'uncertain')),
    confidence DOUBLE PRECISION CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT western_blot_records_identity_key UNIQUE NULLS NOT DISTINCT (
        paper_id,
        candidate_key,
        panel_label,
        row_index,
        lane_index,
        target
    )
);

CREATE INDEX IF NOT EXISTS idx_western_blot_records_target
    ON western_blot_records (lower(target));
CREATE INDEX IF NOT EXISTS idx_western_blot_records_paper
    ON western_blot_records (paper_id);
CREATE INDEX IF NOT EXISTS idx_western_blot_records_recent
    ON western_blot_records (updated_at DESC);
