"""One real PostgreSQL check for importing and browsing a persistent public catalog."""

import os
from types import SimpleNamespace
from uuid import uuid4

import psycopg
import pytest
from fastapi.testclient import TestClient
from psycopg import sql
from psycopg.conninfo import make_conninfo
from psycopg.rows import dict_row

from hiveblot import api, db
from hiveblot.domain import RecordSearchCriteria


def test_public_catalog_preserves_sources_ids_and_failed_imports(monkeypatch, tmp_path):
    database_url = os.environ.get("HIVEBLOT_TEST_DATABASE_URL")
    if not database_url:
        pytest.skip("Set HIVEBLOT_TEST_DATABASE_URL to run the PostgreSQL integration check")
    schema = f"hiveblot_test_{uuid4().hex}"
    scoped_url = make_conninfo(database_url, options=f"-c search_path={schema}")
    with psycopg.connect(database_url, autocommit=True) as admin:
        admin.execute(sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(schema)))
        try:
            _verify_catalog(scoped_url, monkeypatch, tmp_path)
        finally:
            admin.execute(sql.SQL("DROP SCHEMA {} CASCADE").format(sql.Identifier(schema)))


def _verify_catalog(database_url, monkeypatch, tmp_path):
    # Start with the pre-provenance table and data, as an existing installation would.
    with psycopg.connect(database_url) as connection:
        connection.execute("""
            CREATE TABLE western_blot_records (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                paper_id TEXT NOT NULL, candidate_key TEXT NOT NULL,
                source_pdf TEXT, candidate_path TEXT, page INTEGER NOT NULL CHECK (page > 0),
                figure_label TEXT, panel_label TEXT, row_index INTEGER, lane_index INTEGER,
                target TEXT NOT NULL, is_loading_control BOOLEAN NOT NULL DEFAULT FALSE,
                western_blot_type TEXT NOT NULL, sample TEXT, organism TEXT,
                treatment_context TEXT, condition TEXT,
                band_state TEXT NOT NULL CHECK (band_state IN ('present', 'absent', 'uncertain')),
                confidence DOUBLE PRECISION CHECK (confidence BETWEEN 0 AND 1),
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                CONSTRAINT western_blot_records_identity_key UNIQUE NULLS NOT DISTINCT
                    (paper_id, candidate_key, panel_label, row_index, lane_index, target)
            )
        """)
        legacy_id = connection.execute("""
            INSERT INTO western_blot_records
                (paper_id, candidate_key, page, target, western_blot_type, band_state)
            VALUES ('paper-1', 'legacy', 1, 'ACTB', 'western_blot', 'present') RETURNING id
        """).fetchone()[0]
    db.initialize(database_url)
    db.initialize(database_url)
    legacy = db.get_record(database_url, legacy_id)
    assert legacy is not None and legacy["source_id"] is None and legacy["image_sha256"] is None
    legacy_write = _record(
        None, "legacy", panel_label=None, row_index=None, lane_index=None, target="ACTB"
    )
    for field in ("source_id", "image_sha256", "model_version", "source_url"):
        legacy_write.pop(field)
    assert db.replace_records_for_source(database_url, "paper-1", [legacy_write]) == 1
    assert db.get_record(database_url, legacy_id) is not None

    image = tmp_path / "data" / "runs" / "paper-1" / "panel_candidates" / "a.png"
    image.parent.mkdir(parents=True)
    image.write_bytes(b"source image")
    first = _record("a.png", "a-band", candidate_path="runs/paper-1/panel_candidates/a.png")
    stale = {**first, "target": "ACTB", "lane_index": 2}
    second = _record("b.png", "b-band", sample="MCF7", condition="EGF")
    assert (
        db.replace_records_for_source(database_url, "paper-1", [first, stale], source_id="a.png")
        == 2
    )
    assert db.replace_records_for_source(database_url, "paper-1", [second], source_id="b.png") == 1
    rows, total = db.search_records(database_url, RecordSearchCriteria(paper_id="paper-1"))
    assert total == 4
    ids = {(row["source_id"], row["target"]): row["id"] for row in rows}

    # Reimporting an unchanged band keeps its public URL; only the removed band's row disappears.
    db.replace_records_for_source(database_url, "paper-1", [first], source_id="a.png")
    assert db.get_record(database_url, ids[("a.png", "TP53")])["confidence"] == 0.9
    assert db.get_record(database_url, ids[("a.png", "ACTB")]) is None
    assert db.get_record(database_url, ids[("b.png", "TP53")]) is not None
    assert db.get_record(database_url, legacy_id) is not None
    before = _snapshot(database_url)

    for invalid in (
        {**first, "candidate_key": "invalid", "band_state": "invented"},
        {**second, "source_id": "a.png"},
    ):
        with pytest.raises((psycopg.errors.CheckViolation, ValueError)):
            db.replace_records_for_source(
                database_url, "paper-1", [{**first, "confidence": 0.1}, invalid], source_id="a.png"
            )
        assert _snapshot(database_url) == before

    filters = RecordSearchCriteria(
        q="TP53 Nutlin",
        target="TP53",
        sample="A549 cells",
        condition="treated with Nutlin",
        paper_id="paper-1",
    )
    page, total = db.search_records(database_url, filters, limit=1)
    assert total == 1 and page[0]["id"] == ids[("a.png", "TP53")]
    assert db.search_records(database_url, filters, limit=1, offset=10) == ([], 1)
    assert db.search_records(database_url, RecordSearchCriteria(target="' OR TRUE --")) == ([], 0)

    monkeypatch.setattr(
        api,
        "get_settings",
        lambda: SimpleNamespace(database_url=database_url, data_dir=tmp_path / "data"),
    )
    with TestClient(api.app) as client:
        response = client.get(f"/api/records/{page[0]['id']}")
        assert response.status_code == 200
        body = response.json()
        assert body["record"]["doi"] == "10.1000/example"
        assert body["record"]["image_sha256"] == "a" * 64
        assert body["record"]["model_version"] == "fixture@v1"
        assert "candidate_path" not in body["record"] and "source_pdf" not in body["record"]
        assert client.get(body["image_url"]).content == b"source image"
        empty = client.get("/api/records?q=TP53&sample=A549&offset=10").json()
        assert (empty["count"], empty["total"]) == (0, 1)

    # An explicit empty legacy replacement removes NULL-source rows, never named image sources.
    db.replace_records_for_source(database_url, "paper-1", [], source_id=None)
    assert db.get_record(database_url, legacy_id) is None
    assert db.search_records(database_url, RecordSearchCriteria())[1] == 2


def _record(source_id, candidate_key, **overrides):
    return {
        "paper_id": "paper-1",
        "source_id": source_id,
        "candidate_key": candidate_key,
        "source_pdf": "input/paper-1.pdf",
        "candidate_path": None,
        "page": 1,
        "figure_label": "Figure 1",
        "panel_label": "A",
        "row_index": 1,
        "lane_index": 1,
        "target": "TP53",
        "is_loading_control": False,
        "western_blot_type": "western_blot",
        "sample": "A549",
        "organism": "human",
        "treatment_context": None,
        "condition": "Nutlin-3",
        "band_state": "present",
        "confidence": 0.9,
        "image_sha256": "a" * 64,
        "model_version": "fixture@v1",
        "source_url": "https://doi.org/10.1000/example",
        **overrides,
    }


def _snapshot(database_url):
    with psycopg.connect(database_url, row_factory=dict_row) as connection:
        return connection.execute("SELECT * FROM western_blot_records ORDER BY id").fetchall()
