apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: hiveblot
    newName: hiveblot
    newTag: prd-015
patches:
  - path: runtime-config-patch.yaml
  - path: workspace-patch.yaml
  - path: replicas-patch.yaml
  - path: web-service-patch.yaml
  - path: network-policy-patch.yaml
  - path: discovery-patch.yaml
