apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiveblot-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiveblot-web
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiveblot-cpu-workers
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiveblot-workflow-workers
spec:
  replicas: 0
