CREATE TABLE artifact_blobs (
    sha256 TEXT PRIMARY KEY CHECK (sha256 ~ '^[a-f0-9]{64}$'),
    media_type TEXT NOT NULL CHECK (media_type ~ '^[a-z0-9][a-z0-9!#$&^_.+-]*/'),
    byte_size BIGINT NOT NULL CHECK (byte_size >= 0),
    storage_key TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE artifacts (
    artifact_id UUID PRIMARY KEY,
    blob_sha256 TEXT NOT NULL REFERENCES artifact_blobs (sha256),
    original_filename TEXT NOT NULL CHECK (length(btrim(original_filename)) BETWEEN 1 AND 1024),
    source_uri TEXT CHECK (source_uri IS NULL OR length(source_uri) BETWEEN 1 AND 2048),
    acquisition_method TEXT NOT NULL CHECK (
        acquisition_method IN ('user_upload', 'source_adapter')
    ),
    visibility TEXT NOT NULL CHECK (visibility IN ('public', 'organization_private')),
    organization_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT artifact_visibility_scope_check CHECK (
        (visibility = 'public' AND organization_id IS NULL)
        OR (visibility = 'organization_private' AND organization_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX artifacts_content_scope_key
    ON artifacts (
        blob_sha256,
        visibility,
        COALESCE(organization_id, '00000000-0000-0000-0000-000000000000'::uuid)
    );

CREATE TABLE artifact_relationships (
    artifact_id UUID NOT NULL REFERENCES artifacts (artifact_id),
    related_artifact_id UUID NOT NULL REFERENCES artifacts (artifact_id),
    relationship_kind TEXT NOT NULL CHECK (
        relationship_kind IN ('parent', 'related', 'derived_from', 'supplement_to')
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (artifact_id, related_artifact_id, relationship_kind),
    CHECK (artifact_id <> related_artifact_id)
);

CREATE TABLE artifact_uploads (
    upload_id UUID PRIMARY KEY,
    backend_upload_id TEXT,
    staging_key TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL CHECK (
        status IN ('initiated', 'validating', 'published', 'failed', 'aborted')
    ),
    original_filename TEXT NOT NULL CHECK (length(btrim(original_filename)) BETWEEN 1 AND 1024),
    declared_media_type TEXT,
    expected_byte_size BIGINT CHECK (expected_byte_size IS NULL OR expected_byte_size >= 0),
    source_uri TEXT,
    acquisition_method TEXT NOT NULL CHECK (
        acquisition_method IN ('user_upload', 'source_adapter')
    ),
    visibility TEXT NOT NULL CHECK (visibility IN ('public', 'organization_private')),
    organization_id UUID,
    relationships JSONB NOT NULL DEFAULT '[]'::jsonb,
    validated_sha256 TEXT CHECK (
        validated_sha256 IS NULL OR validated_sha256 ~ '^[a-f0-9]{64}$'
    ),
    validated_media_type TEXT,
    validated_byte_size BIGINT CHECK (validated_byte_size IS NULL OR validated_byte_size >= 0),
    artifact_id UUID REFERENCES artifacts (artifact_id),
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT artifact_upload_visibility_scope_check CHECK (
        (visibility = 'public' AND organization_id IS NULL)
        OR (visibility = 'organization_private' AND organization_id IS NOT NULL)
    ),
    CONSTRAINT artifact_upload_publication_check CHECK (
        (status = 'published' AND artifact_id IS NOT NULL)
        OR (status <> 'published' AND artifact_id IS NULL)
    )
);

CREATE INDEX artifact_uploads_incomplete_idx
    ON artifact_uploads (expires_at)
    WHERE status IN ('initiated', 'validating');

CREATE TABLE artifact_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id UUID REFERENCES artifacts (artifact_id),
    upload_id UUID REFERENCES artifact_uploads (upload_id),
    event_type TEXT NOT NULL CHECK (
        event_type IN (
            'upload_initiated',
            'upload_aborted',
            'upload_failed',
            'artifact_created',
            'artifact_deduplicated',
            'access_url_created'
        )
    ),
    actor_id UUID,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (artifact_id IS NOT NULL OR upload_id IS NOT NULL)
);

CREATE INDEX artifact_events_artifact_time_idx
    ON artifact_events (artifact_id, created_at DESC)
    WHERE artifact_id IS NOT NULL;
