DROP TABLE pipeline_publication_output_artifacts;
DROP TABLE pipeline_publications;
DROP TABLE component_invocation_evidence_artifacts;
DROP TABLE component_invocation_output_artifacts;
DROP TABLE component_invocation_input_artifacts;
DROP TABLE component_invocation_parents;
DROP TABLE component_invocations;
DROP TABLE pipeline_run_input_artifacts;
DROP TABLE pipeline_runs;
DROP TABLE pipeline_definitions;
DELETE FROM schema_migrations WHERE version = '0007_pipeline_run_registry';
