"""Canonical, strict Pydantic v2 contracts for HiveBlot boundaries."""

from .annotations import (
    AdjudicationRecord,
    AnnotationDocumentRecord,
    AnnotationErrorCode,
    AnnotationRelationship,
    AnnotationRevision,
    AnnotationScalar,
    CaseArtifactRole,
    CaseSourceArtifact,
    EntityFieldTarget,
    EvaluationCaseRecord,
    FieldAnnotation,
    FieldAnnotationTarget,
    FieldPathTarget,
    ObservationState,
    PredictionDocument,
    PredictionEvidence,
    ReviewerAssignment,
    ReviewerAssignmentStatus,
    ReviewStatus,
    SpatialAnnotation,
    SpatialAnnotationType,
)
from .artifacts import (
    ArtifactAcquisitionMethod,
    ArtifactRecord,
    ArtifactReference,
    ArtifactRelationship,
    ArtifactRelationshipKind,
    ArtifactVisibility,
    BoundingRegion,
    SourceDocumentKind,
    SourceDocumentRecord,
)
from .base import SCHEMA_VERSION, ContractModel, SchemaVersion
from .evaluation import EvaluationCaseReference, ValidationIssue, ValidationSeverity
from .identifiers import ModelIdentifier, PipelineIdentifier, ProducerIdentifier, ToolIdentifier
from .jobs import (
    CancelledJobResult,
    ContainerSpecification,
    ExpectedJobOutput,
    FailedJobResult,
    JobError,
    JobResult,
    JobSpecification,
    NamedArtifactReference,
    NetworkPolicy,
    ResourceRequirements,
    SucceededJobResult,
)

__all__ = [
    "SCHEMA_VERSION",
    "AdjudicationRecord",
    "AnnotationDocumentRecord",
    "AnnotationErrorCode",
    "AnnotationRelationship",
    "AnnotationRevision",
    "AnnotationScalar",
    "ArtifactAcquisitionMethod",
    "ArtifactRecord",
    "ArtifactReference",
    "ArtifactRelationship",
    "ArtifactRelationshipKind",
    "ArtifactVisibility",
    "BoundingRegion",
    "CaseArtifactRole",
    "CaseSourceArtifact",
    "CancelledJobResult",
    "ContainerSpecification",
    "ContractModel",
    "EvaluationCaseReference",
    "EvaluationCaseRecord",
    "ExpectedJobOutput",
    "EntityFieldTarget",
    "FailedJobResult",
    "FieldAnnotation",
    "FieldAnnotationTarget",
    "FieldPathTarget",
    "JobError",
    "JobResult",
    "JobSpecification",
    "ModelIdentifier",
    "NamedArtifactReference",
    "NetworkPolicy",
    "ObservationState",
    "PipelineIdentifier",
    "ProducerIdentifier",
    "PredictionDocument",
    "PredictionEvidence",
    "ResourceRequirements",
    "ReviewerAssignment",
    "ReviewerAssignmentStatus",
    "ReviewStatus",
    "SchemaVersion",
    "SourceDocumentKind",
    "SourceDocumentRecord",
    "SpatialAnnotation",
    "SpatialAnnotationType",
    "SucceededJobResult",
    "ToolIdentifier",
    "ValidationIssue",
    "ValidationSeverity",
]
